name: Build, Push to JFrog, and Deploy to ACI

on:
  push:
    branches:
      - main
      
jobs:
  build-tag-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      - name: Build, Tag, and Push Docker Image
        env:
          IMAGE_NAME: trialvu3lnk.jfrog.io/testv1-docker/jfrog-docker-example-image:${{ github.run_number }}
        run: |
          jf docker build -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME

      - name: Publish Build Info with JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jfrog-docker-build-example
          JFROG_CLI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          jf rt build-collect-env
          jf rt build-add-git
          jf rt build-publish

      # 🔥 NEW PART: Deploy to Azure Container Instance (ACI)

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instance
        env:
          IMAGE_NAME: trialvu3lnk.jfrog.io/testv1-docker/jfrog-docker-example-image:${{ github.run_number }}
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name my-container-${{ github.run_number }} \
            --image $IMAGE_NAME \
            --registry-login-server trialvu3lnk.jfrog.io \
            --registry-username ${{ secrets.JF_USER }} \
            --registry-password ${{ secrets.JF_PASSWORD }} \
            --dns-name-label my-container-${{ github.run_number }}-dns \
            --ports 80
